apiVersion: v1
kind: ServiceAccount
metadata:
  name: gameserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gameserver-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gameserver-role-binding
subjects:
  - kind: ServiceAccount
    name: gameserver
    namespace: default
roleRef:
  kind: ClusterRole
  name: gameserver-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.docker.project: koncord
  name: koncord
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: koncord
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.docker.project: koncord
    spec:
      serviceAccountName: gameserver
      containers:
        - name: hello
          image: koncord:dev
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}
